version: "3.7"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: codesanook-example-db:latest
    container_name: sql-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD:?err}"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
